#!/usr/bin/env python3
"""One-time cutover importer: old SQLite registry -> Postgres seed SQL.

Reads registry/experiments.sqlite (the live legacy store) and emits a Postgres
INSERT script targeting the new schema (migrations/0001_init.sql). Stdlib only.

  python3 import_from_sqlite.py [registry/experiments.sqlite] > seed_from_sqlite.sql
  # then, after `supabase db reset`:  psql "$DATABASE_URL" -f seed_from_sqlite.sql

Legacy rows have no contributor/box/seed-pairing — those columns import as NULL,
which (correctly) leaves every legacy comparison is_paired = FALSE: the old
deltas were never seed/box-paired, so they stay untrusted. Status vocab is
remapped to the new CHECK constraints. config (legacy free-text) is wrapped as
jsonb {"legacy": "<text>"}.
"""
from __future__ import annotations

import sqlite3
import sys

# old status vocab -> new CHECK-constrained vocab
RUN_STATUS = {"completed": "done", "stopped": "failed"}
QUEUE_STATUS = {"planned": "needs-run", "running": "running", "done": "done",
                "failed": "failed", "cancelled": "cancelled"}
IDEA_STATUS = {"queued": "needs-run", "proposed": "proposed", "done": "done",
               "rejected": "rejected", "running": "running"}
THREAD_STATUS = {"active": "active", "planning": "active", "paused": "paused",
                 "done": "closed", "closed": "closed"}


def q(v) -> str:
    """SQL literal for a value (NULL / quoted-escaped string)."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def jsonb(v) -> str:
    if v is None:
        return "NULL"
    return q('{"legacy": ' + _json_str(str(v)) + "}") + "::jsonb"


def _json_str(s: str) -> str:
    out = '"'
    for ch in s:
        if ch in '"\\':
            out += "\\" + ch
        elif ch == "\n":
            out += "\\n"
        else:
            out += ch
    return out + '"'


def boolean(v) -> str:
    if v is None:
        return "NULL"
    return "TRUE" if v else "FALSE"


def cols(row, names):
    return {n: (row[n] if n in row.keys() else None) for n in names}


def main(path: str) -> None:
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    w = sys.stdout.write

    w("-- voidbase seed: imported from legacy SQLite registry.\n")
    w("-- Generated by import_from_sqlite.py. ON CONFLICT DO NOTHING = re-runnable.\n")
    w("begin;\n\n")

    w("-- threads\n")
    for r in c.execute("select * from threads"):
        d = cols(r, ["name", "hypothesis", "status", "priority", "notes_path",
                     "summary", "created_at", "updated_at"])
        w(f"insert into threads (name, hypothesis, status, priority, notes_path, "
          f"summary, created_at, updated_at) values ("
          f"{q(d['name'])}, {q(d['hypothesis'])}, "
          f"{q(THREAD_STATUS.get(d['status'], 'active'))}, {q(d['priority'] or 0)}, "
          f"{q(d['notes_path'])}, {q(d['summary'])}, "
          f"{q(d['created_at'])}, {q(d['updated_at'])}) on conflict (name) do nothing;\n")

    w("\n-- ideas\n")
    for r in c.execute("select * from ideas"):
        d = cols(r, ["id", "title", "explanation", "status", "notes", "created_at"])
        w(f"insert into ideas (id, title, explanation, status, notes, created_at) values ("
          f"{q(d['id'])}, {q(d['title'])}, {q(d['explanation'])}, "
          f"{q(IDEA_STATUS.get(d['status'], 'proposed'))}, {q(d['notes'])}, "
          f"{q(d['created_at'])}) on conflict (id) do nothing;\n")

    w("\n-- queue_items\n")
    for r in c.execute("select * from queue_items"):
        d = cols(r, ["id", "thread_name", "name", "command", "status", "priority",
                     "gpu_class", "created_at", "started_at", "finished_at",
                     "log_path", "output_dir", "decision"])
        w(f"insert into queue_items (id, thread_name, name, command, status, priority, "
          f"gpu_class, created_at, started_at, finished_at, log_path, output_dir, decision) values ("
          f"{q(d['id'])}, {q(d['thread_name'])}, {q(d['name'])}, {q(d['command'])}, "
          f"{q(QUEUE_STATUS.get(d['status'], 'needs-run'))}, {q(d['priority'] or 0)}, "
          f"{q(d['gpu_class'])}, {q(d['created_at'])}, {q(d['started_at'])}, "
          f"{q(d['finished_at'])}, {q(d['log_path'])}, {q(d['output_dir'])}, "
          f"{q(d['decision'])}) on conflict (id) do nothing;\n")

    w("\n-- runs (verification defaults to 'unverified'; legacy = no pairing record)\n")
    for r in c.execute("select * from runs"):
        d = cols(r, ["id", "queue_item_id", "thread_name", "name", "command", "config",
                     "seed", "tokens_target", "tokens_seen", "actual_steps", "status",
                     "verdict", "output_dir", "metrics_path", "checkpoint_path",
                     "final_val_loss", "final_val_accuracy", "final_train_loss",
                     "git_commit", "git_branch", "git_dirty", "created_at", "finished_at"])
        w(f"insert into runs (id, queue_item_id, thread_name, name, command, config, seed, "
          f"tokens_target, tokens_seen, actual_steps, status, verdict, output_dir, "
          f"metrics_path, checkpoint_path, final_val_loss, final_val_accuracy, "
          f"final_train_loss, git_commit, git_branch, git_dirty, created_at, finished_at) values ("
          f"{q(d['id'])}, {q(d['queue_item_id'])}, {q(d['thread_name'])}, {q(d['name'])}, "
          f"{q(d['command'])}, {jsonb(d['config'])}, {q(d['seed'])}, {q(d['tokens_target'])}, "
          f"{q(d['tokens_seen'])}, {q(d['actual_steps'])}, "
          f"{q(RUN_STATUS.get(d['status'], 'done'))}, {q(d['verdict'])}, {q(d['output_dir'])}, "
          f"{q(d['metrics_path'])}, {q(d['checkpoint_path'])}, {q(d['final_val_loss'])}, "
          f"{q(d['final_val_accuracy'])}, {q(d['final_train_loss'])}, {q(d['git_commit'])}, "
          f"{q(d['git_branch'])}, {boolean(d['git_dirty'])}, {q(d['created_at'])}, "
          f"{q(d['finished_at'])}) on conflict (id) do nothing;\n")

    w("\n-- eval_points\n")
    for r in c.execute("select * from eval_points"):
        d = cols(r, ["run_id", "step", "tokens", "val_loss", "val_accuracy",
                     "val_perplexity", "learning_rate", "elapsed_seconds", "created_at"])
        w(f"insert into eval_points (run_id, step, tokens, val_loss, val_accuracy, "
          f"val_perplexity, learning_rate, elapsed_seconds, created_at) values ("
          f"{q(d['run_id'])}, {q(d['step'])}, {q(d['tokens'])}, {q(d['val_loss'])}, "
          f"{q(d['val_accuracy'])}, {q(d['val_perplexity'])}, {q(d['learning_rate'])}, "
          f"{q(d['elapsed_seconds'])}, {q(d['created_at'])});\n")

    w("\n-- comparisons (legacy: seed/box NULL -> is_paired computes FALSE)\n")
    for r in c.execute("select * from comparisons"):
        d = cols(r, ["run_id", "baseline_name", "baseline_run_id", "matched_step",
                     "matched_tokens", "baseline_val_loss", "run_val_loss",
                     "delta_val_loss", "verdict", "created_at"])
        w(f"insert into comparisons (run_id, baseline_name, baseline_run_id, matched_step, "
          f"matched_tokens, baseline_val_loss, run_val_loss, delta_val_loss, verdict, created_at) values ("
          f"{q(d['run_id'])}, {q(d['baseline_name'])}, {q(d['baseline_run_id'])}, "
          f"{q(d['matched_step'])}, {q(d['matched_tokens'])}, {q(d['baseline_val_loss'])}, "
          f"{q(d['run_val_loss'])}, {q(d['delta_val_loss'])}, {q(d['verdict'])}, "
          f"{q(d['created_at'])});\n")

    w("\n-- decisions\n")
    for r in c.execute("select * from decisions"):
        d = cols(r, ["thread_name", "run_id", "decision", "reason", "decided_by", "decided_at"])
        w(f"insert into decisions (thread_name, run_id, decision, reason, decided_at) values ("
          f"{q(d['thread_name'])}, {q(d['run_id'])}, {q(d['decision'])}, {q(d['reason'])}, "
          f"{q(d['decided_at'])});\n")

    w("\ncommit;\n")
    conn.close()


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "registry/experiments.sqlite")
